export const CHAPTER_DATA: Record<
  string,
  Array<{
    number: number;
    englishName: string;
    hebrewName: string;
    startFolio: number;
    startSide: "a" | "b";
    endFolio: number;
    endSide: "a" | "b";
  }>
> = {
  arakhin: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 7,
      endSide: "b",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 7,
      startSide: "b",
      endFolio: 13,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 13,
      startSide: "b",
      endFolio: 17,
      endSide: "a",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 17,
      startSide: "a",
      endFolio: 19,
      endSide: "a",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 19,
      startSide: "a",
      endFolio: 21,
      endSide: "b",
    },
    {
      number: 6,
      englishName: "Chapter 6",
      hebrewName: "פרק ו",
      startFolio: 21,
      startSide: "b",
      endFolio: 24,
      endSide: "a",
    },
    {
      number: 7,
      englishName: "Chapter 7",
      hebrewName: "פרק ז",
      startFolio: 24,
      startSide: "a",
      endFolio: 27,
      endSide: "a",
    },
    {
      number: 8,
      englishName: "Chapter 8",
      hebrewName: "פרק ח",
      startFolio: 27,
      startSide: "a",
      endFolio: 29,
      endSide: "a",
    },
    {
      number: 9,
      englishName: "Chapter 9",
      hebrewName: "פרק ט",
      startFolio: 29,
      startSide: "b",
      endFolio: 34,
      endSide: "a",
    },
  ],
  "avodah zarah": [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 22,
      endSide: "a",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 22,
      startSide: "a",
      endFolio: 40,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 40,
      startSide: "b",
      endFolio: 49,
      endSide: "b",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 49,
      startSide: "b",
      endFolio: 61,
      endSide: "b",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 62,
      startSide: "a",
      endFolio: 76,
      endSide: "b",
    },
  ],
  "bava batra": [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 17,
      endSide: "a",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 17,
      startSide: "a",
      endFolio: 27,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 28,
      startSide: "a",
      endFolio: 60,
      endSide: "b",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 61,
      startSide: "a",
      endFolio: 73,
      endSide: "a",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 73,
      startSide: "a",
      endFolio: 91,
      endSide: "b",
    },
    {
      number: 6,
      englishName: "Chapter 6",
      hebrewName: "פרק ו",
      startFolio: 92,
      startSide: "a",
      endFolio: 102,
      endSide: "b",
    },
    {
      number: 7,
      englishName: "Chapter 7",
      hebrewName: "פרק ז",
      startFolio: 102,
      startSide: "b",
      endFolio: 108,
      endSide: "a",
    },
    {
      number: 8,
      englishName: "Chapter 8",
      hebrewName: "פרק ח",
      startFolio: 108,
      startSide: "a",
      endFolio: 139,
      endSide: "b",
    },
    {
      number: 9,
      englishName: "Chapter 9",
      hebrewName: "פרק ט",
      startFolio: 139,
      startSide: "b",
      endFolio: 159,
      endSide: "b",
    },
    {
      number: 10,
      englishName: "Chapter 10",
      hebrewName: "פרק י",
      startFolio: 160,
      startSide: "a",
      endFolio: 176,
      endSide: "b",
    },
  ],
  "bava kamma": [
    {
      number: 1,
      englishName: "Arba'ah Avot",
      hebrewName: "פרק א - ארבעה אבות",
      startFolio: 2,
      startSide: "a",
      endFolio: 17,
      endSide: "a",
    },
    {
      number: 2,
      englishName: "Keytzad HaRegel",
      hebrewName: "פרק ב - כיצד הרגל",
      startFolio: 17,
      startSide: "a",
      endFolio: 27,
      endSide: "a",
    },
    {
      number: 3,
      englishName: "HaMani'ach Et HaKad",
      hebrewName: "פרק ג - המניח את הכד",
      startFolio: 27,
      startSide: "a",
      endFolio: 36,
      endSide: "a",
    },
    {
      number: 4,
      englishName: "Shor She'nagach",
      hebrewName: "פרק ד - שור שנגח ד' וה'",
      startFolio: 36,
      startSide: "a",
      endFolio: 46,
      endSide: "a",
    },
    {
      number: 5,
      englishName: "Shor She'nagach Et HaParah",
      hebrewName: "פרק ה - שור שנגח את הפרה",
      startFolio: 46,
      startSide: "a",
      endFolio: 55,
      endSide: "a",
    },
    {
      number: 6,
      englishName: "HaKoneis",
      hebrewName: "פרק ו - הכונס",
      startFolio: 55,
      startSide: "b",
      endFolio: 62,
      endSide: "b",
    },
    {
      number: 7,
      englishName: "Merubah",
      hebrewName: "פרק ז - מרובה",
      startFolio: 62,
      startSide: "b",
      endFolio: 83,
      endSide: "a",
    },
    {
      number: 8,
      englishName: "HaChovel",
      hebrewName: "פרק ח - החובל",
      startFolio: 83,
      startSide: "b",
      endFolio: 93,
      endSide: "a",
    },
    {
      number: 9,
      englishName: "HaGozel Etzim",
      hebrewName: "פרק ט - הגוזל עצים",
      startFolio: 93,
      startSide: "b",
      endFolio: 111,
      endSide: "a",
    },
    {
      number: 10,
      englishName: "HaGozel UMa'akhil",
      hebrewName: "פרק י - הגוזל ומאכיל",
      startFolio: 111,
      startSide: "b",
      endFolio: 119,
      endSide: "b",
    },
  ],
  "bava metzia": [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 21,
      endSide: "a",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 21,
      startSide: "a",
      endFolio: 33,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 33,
      startSide: "b",
      endFolio: 44,
      endSide: "a",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 44,
      startSide: "a",
      endFolio: 60,
      endSide: "b",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 60,
      startSide: "b",
      endFolio: 75,
      endSide: "b",
    },
    {
      number: 6,
      englishName: "Chapter 6",
      hebrewName: "פרק ו",
      startFolio: 75,
      startSide: "b",
      endFolio: 83,
      endSide: "a",
    },
    {
      number: 7,
      englishName: "Chapter 7",
      hebrewName: "פרק ז",
      startFolio: 83,
      startSide: "a",
      endFolio: 94,
      endSide: "a",
    },
    {
      number: 8,
      englishName: "Chapter 8",
      hebrewName: "פרק ח",
      startFolio: 94,
      startSide: "a",
      endFolio: 103,
      endSide: "a",
    },
    {
      number: 9,
      englishName: "Chapter 9",
      hebrewName: "פרק ט",
      startFolio: 103,
      startSide: "a",
      endFolio: 116,
      endSide: "a",
    },
    {
      number: 10,
      englishName: "Chapter 10",
      hebrewName: "פרק י",
      startFolio: 116,
      startSide: "b",
      endFolio: 119,
      endSide: "a",
    },
  ],
  beitza: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 15,
      endSide: "a",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 15,
      startSide: "b",
      endFolio: 23,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 23,
      startSide: "b",
      endFolio: 29,
      endSide: "b",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 29,
      startSide: "b",
      endFolio: 35,
      endSide: "b",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 35,
      startSide: "b",
      endFolio: 40,
      endSide: "b",
    },
  ],
  bekhorot: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 13,
      endSide: "a",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 13,
      startSide: "a",
      endFolio: 19,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 19,
      startSide: "b",
      endFolio: 26,
      endSide: "b",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 26,
      startSide: "b",
      endFolio: 31,
      endSide: "a",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 31,
      startSide: "a",
      endFolio: 37,
      endSide: "a",
    },
    {
      number: 6,
      englishName: "Chapter 6",
      hebrewName: "פרק ו",
      startFolio: 37,
      startSide: "a",
      endFolio: 43,
      endSide: "a",
    },
    {
      number: 7,
      englishName: "Chapter 7",
      hebrewName: "פרק ז",
      startFolio: 43,
      startSide: "a",
      endFolio: 46,
      endSide: "a",
    },
    {
      number: 8,
      englishName: "Chapter 8",
      hebrewName: "פרק ח",
      startFolio: 46,
      startSide: "a",
      endFolio: 52,
      endSide: "b",
    },
    {
      number: 9,
      englishName: "Chapter 9",
      hebrewName: "פרק ט",
      startFolio: 53,
      startSide: "a",
      endFolio: 61,
      endSide: "a",
    },
  ],
  berakhot: [
    {
      number: 1,
      englishName: "Me'eimatay",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 13,
      endSide: "a",
    },
    {
      number: 2,
      englishName: "Hayah Korei",
      hebrewName: "פרק ב",
      startFolio: 13,
      startSide: "a",
      endFolio: 17,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Mi She'meto",
      hebrewName: "פרק ג",
      startFolio: 17,
      startSide: "b",
      endFolio: 26,
      endSide: "a",
    },
    {
      number: 4,
      englishName: "Tefilat HaShachar",
      hebrewName: "פרק ד",
      startFolio: 26,
      startSide: "a",
      endFolio: 30,
      endSide: "b",
    },
    {
      number: 5,
      englishName: "Ein Omdin",
      hebrewName: "פרק ה",
      startFolio: 30,
      startSide: "b",
      endFolio: 34,
      endSide: "b",
    },
    {
      number: 6,
      englishName: "Keytzad Mevarkhim",
      hebrewName: "פרק ו",
      startFolio: 35,
      startSide: "a",
      endFolio: 45,
      endSide: "a",
    },
    {
      number: 7,
      englishName: "Sheloshah She'achlu",
      hebrewName: "פרק ז",
      startFolio: 45,
      startSide: "a",
      endFolio: 51,
      endSide: "b",
    },
    {
      number: 8,
      englishName: "Eilu Devarim",
      hebrewName: "פרק ח",
      startFolio: 51,
      startSide: "b",
      endFolio: 53,
      endSide: "b",
    },
    {
      number: 9,
      englishName: "HaRo'eh",
      hebrewName: "פרק ט",
      startFolio: 54,
      startSide: "a",
      endFolio: 64,
      endSide: "a",
    },
  ],
  chagigah: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 11,
      endSide: "b",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 11,
      startSide: "b",
      endFolio: 20,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 20,
      startSide: "b",
      endFolio: 27,
      endSide: "a",
    },
  ],
  chullin: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א - הכל שוחטין",
      startFolio: 2,
      startSide: "a",
      endFolio: 26,
      endSide: "b",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב - השוחט",
      startFolio: 27,
      startSide: "a",
      endFolio: 42,
      endSide: "a",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג - אלו טריפות",
      startFolio: 42,
      startSide: "a",
      endFolio: 67,
      endSide: "b",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד - בהמה המקשה",
      startFolio: 68,
      startSide: "a",
      endFolio: 78,
      endSide: "a",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה - אותו ואת בנו",
      startFolio: 78,
      startSide: "a",
      endFolio: 83,
      endSide: "b",
    },
    {
      number: 6,
      englishName: "Chapter 6",
      hebrewName: "פרק ו - כיסוי הדם",
      startFolio: 83,
      startSide: "b",
      endFolio: 89,
      endSide: "b",
    },
    {
      number: 7,
      englishName: "Chapter 7",
      hebrewName: "פרק ז - גיד הנשה",
      startFolio: 89,
      startSide: "b",
      endFolio: 103,
      endSide: "b",
    },
    {
      number: 8,
      englishName: "Chapter 8",
      hebrewName: "פרק ח - כל הבשר",
      startFolio: 103,
      startSide: "b",
      endFolio: 117,
      endSide: "b",
    },
    {
      number: 9,
      englishName: "Chapter 9",
      hebrewName: "פרק ט - העור והרוטב",
      startFolio: 117,
      startSide: "b",
      endFolio: 129,
      endSide: "b",
    },
    {
      number: 10,
      englishName: "Chapter 10",
      hebrewName: "פרק י - הזרוע הלחיים והקיבה",
      startFolio: 130,
      startSide: "a",
      endFolio: 134,
      endSide: "b",
    },
    {
      number: 11,
      englishName: "Chapter 11",
      hebrewName: "פרק יא - ראשית הגז",
      startFolio: 135,
      startSide: "a",
      endFolio: 138,
      endSide: "b",
    },
    {
      number: 12,
      englishName: "Chapter 12",
      hebrewName: "פרק יב - שילוח הקן",
      startFolio: 138,
      startSide: "b",
      endFolio: 142,
      endSide: "a",
    },
  ],
  eruvin: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 17,
      endSide: "b",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 17,
      startSide: "b",
      endFolio: 26,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 26,
      startSide: "b",
      endFolio: 41,
      endSide: "b",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 41,
      startSide: "b",
      endFolio: 52,
      endSide: "b",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 52,
      startSide: "b",
      endFolio: 61,
      endSide: "b",
    },
    {
      number: 6,
      englishName: "Chapter 6",
      hebrewName: "פרק ו",
      startFolio: 61,
      startSide: "b",
      endFolio: 76,
      endSide: "a",
    },
    {
      number: 7,
      englishName: "Chapter 7",
      hebrewName: "פרק ז",
      startFolio: 76,
      startSide: "a",
      endFolio: 82,
      endSide: "a",
    },
    {
      number: 8,
      englishName: "Chapter 8",
      hebrewName: "פרק ח",
      startFolio: 82,
      startSide: "a",
      endFolio: 89,
      endSide: "a",
    },
    {
      number: 9,
      englishName: "Chapter 9",
      hebrewName: "פרק ט",
      startFolio: 89,
      startSide: "a",
      endFolio: 95,
      endSide: "a",
    },
    {
      number: 10,
      englishName: "Chapter 10",
      hebrewName: "פרק י",
      startFolio: 95,
      startSide: "a",
      endFolio: 105,
      endSide: "a",
    },
  ],
  gittin: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 15,
      endSide: "a",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 15,
      startSide: "a",
      endFolio: 24,
      endSide: "a",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 24,
      startSide: "a",
      endFolio: 32,
      endSide: "a",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 32,
      startSide: "a",
      endFolio: 48,
      endSide: "b",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 48,
      startSide: "b",
      endFolio: 62,
      endSide: "a",
    },
    {
      number: 6,
      englishName: "Chapter 6",
      hebrewName: "פרק ו",
      startFolio: 62,
      startSide: "b",
      endFolio: 67,
      endSide: "b",
    },
    {
      number: 7,
      englishName: "Chapter 7",
      hebrewName: "פרק ז",
      startFolio: 67,
      startSide: "b",
      endFolio: 77,
      endSide: "a",
    },
    {
      number: 8,
      englishName: "Chapter 8",
      hebrewName: "פרק ח",
      startFolio: 77,
      startSide: "a",
      endFolio: 82,
      endSide: "a",
    },
    {
      number: 9,
      englishName: "Chapter 9",
      hebrewName: "פרק ט",
      startFolio: 82,
      startSide: "a",
      endFolio: 90,
      endSide: "b",
    },
  ],
  horayot: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 6,
      endSide: "b",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 6,
      startSide: "b",
      endFolio: 9,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 9,
      startSide: "b",
      endFolio: 14,
      endSide: "a",
    },
  ],
  keritot: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 8,
      endSide: "b",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 8,
      startSide: "b",
      endFolio: 11,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 11,
      startSide: "b",
      endFolio: 17,
      endSide: "a",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 17,
      startSide: "a",
      endFolio: 20,
      endSide: "b",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 20,
      startSide: "b",
      endFolio: 23,
      endSide: "b",
    },
    {
      number: 6,
      englishName: "Chapter 6",
      hebrewName: "פרק ו",
      startFolio: 23,
      startSide: "b",
      endFolio: 28,
      endSide: "b",
    },
  ],
  ketubot: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 15,
      endSide: "b",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 15,
      startSide: "b",
      endFolio: 28,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 29,
      startSide: "a",
      endFolio: 41,
      endSide: "b",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 41,
      startSide: "b",
      endFolio: 54,
      endSide: "b",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 54,
      startSide: "b",
      endFolio: 65,
      endSide: "b",
    },
    {
      number: 6,
      englishName: "Chapter 6",
      hebrewName: "פרק ו",
      startFolio: 65,
      startSide: "b",
      endFolio: 70,
      endSide: "a",
    },
    {
      number: 7,
      englishName: "Chapter 7",
      hebrewName: "פרק ז",
      startFolio: 70,
      startSide: "a",
      endFolio: 77,
      endSide: "b",
    },
    {
      number: 8,
      englishName: "Chapter 8",
      hebrewName: "פרק ח",
      startFolio: 78,
      startSide: "a",
      endFolio: 82,
      endSide: "b",
    },
    {
      number: 9,
      englishName: "Chapter 9",
      hebrewName: "פרק ט",
      startFolio: 83,
      startSide: "a",
      endFolio: 90,
      endSide: "a",
    },
    {
      number: 10,
      englishName: "Chapter 10",
      hebrewName: "פרק י",
      startFolio: 90,
      startSide: "a",
      endFolio: 95,
      endSide: "b",
    },
    {
      number: 11,
      englishName: "Chapter 11",
      hebrewName: "פרק יא",
      startFolio: 95,
      startSide: "b",
      endFolio: 101,
      endSide: "b",
    },
    {
      number: 12,
      englishName: "Chapter 12",
      hebrewName: "פרק יב",
      startFolio: 101,
      startSide: "b",
      endFolio: 104,
      endSide: "b",
    },
    {
      number: 13,
      englishName: "Chapter 13",
      hebrewName: "פרק יג",
      startFolio: 104,
      startSide: "b",
      endFolio: 112,
      endSide: "b",
    },
  ],
  kiddushin: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 41,
      endSide: "a",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 41,
      startSide: "a",
      endFolio: 58,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 58,
      startSide: "b",
      endFolio: 69,
      endSide: "a",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 69,
      startSide: "a",
      endFolio: 82,
      endSide: "b",
    },
  ],
  makkot: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 7,
      endSide: "a",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 7,
      startSide: "a",
      endFolio: 13,
      endSide: "a",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 13,
      startSide: "a",
      endFolio: 24,
      endSide: "b",
    },
  ],
  megillah: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 17,
      endSide: "a",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 17,
      startSide: "a",
      endFolio: 21,
      endSide: "a",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 21,
      startSide: "a",
      endFolio: 25,
      endSide: "b",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 25,
      startSide: "b",
      endFolio: 32,
      endSide: "a",
    },
  ],
  meilah: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 8,
      endSide: "a",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 8,
      startSide: "a",
      endFolio: 10,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 10,
      startSide: "b",
      endFolio: 14,
      endSide: "b",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 15,
      startSide: "a",
      endFolio: 18,
      endSide: "a",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 18,
      startSide: "a",
      endFolio: 20,
      endSide: "a",
    },
    {
      number: 6,
      englishName: "Chapter 6",
      hebrewName: "פרק ו",
      startFolio: 20,
      startSide: "a",
      endFolio: 22,
      endSide: "a",
    },
  ],
  menachot: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 13,
      endSide: "a",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 13,
      startSide: "a",
      endFolio: 17,
      endSide: "a",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 17,
      startSide: "a",
      endFolio: 38,
      endSide: "a",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 38,
      startSide: "a",
      endFolio: 52,
      endSide: "b",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 52,
      startSide: "b",
      endFolio: 63,
      endSide: "b",
    },
    {
      number: 6,
      englishName: "Chapter 6",
      hebrewName: "פרק ו",
      startFolio: 63,
      startSide: "b",
      endFolio: 72,
      endSide: "b",
    },
    {
      number: 7,
      englishName: "Chapter 7",
      hebrewName: "פרק ז",
      startFolio: 72,
      startSide: "b",
      endFolio: 76,
      endSide: "b",
    },
    {
      number: 8,
      englishName: "Chapter 8",
      hebrewName: "פרק ח",
      startFolio: 76,
      startSide: "b",
      endFolio: 83,
      endSide: "b",
    },
    {
      number: 9,
      englishName: "Chapter 9",
      hebrewName: "פרק ט",
      startFolio: 83,
      startSide: "b",
      endFolio: 87,
      endSide: "a",
    },
    {
      number: 10,
      englishName: "Chapter 10",
      hebrewName: "פרק י",
      startFolio: 87,
      startSide: "a",
      endFolio: 94,
      endSide: "a",
    },
    {
      number: 11,
      englishName: "Chapter 11",
      hebrewName: "פרק יא",
      startFolio: 94,
      startSide: "a",
      endFolio: 100,
      endSide: "b",
    },
    {
      number: 12,
      englishName: "Chapter 12",
      hebrewName: "פרק יב",
      startFolio: 100,
      startSide: "b",
      endFolio: 104,
      endSide: "b",
    },
    {
      number: 13,
      englishName: "Chapter 13",
      hebrewName: "פרק יג",
      startFolio: 104,
      startSide: "b",
      endFolio: 110,
      endSide: "a",
    },
  ],
  "moed katan": [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 11,
      endSide: "a",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 11,
      startSide: "b",
      endFolio: 13,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 13,
      startSide: "b",
      endFolio: 29,
      endSide: "a",
    },
  ],
  nazir: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 8,
      endSide: "b",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 9,
      startSide: "a",
      endFolio: 16,
      endSide: "a",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 16,
      startSide: "a",
      endFolio: 20,
      endSide: "b",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 20,
      startSide: "b",
      endFolio: 30,
      endSide: "b",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 30,
      startSide: "b",
      endFolio: 34,
      endSide: "a",
    },
    {
      number: 6,
      englishName: "Chapter 6",
      hebrewName: "פרק ו",
      startFolio: 34,
      startSide: "a",
      endFolio: 47,
      endSide: "a",
    },
    {
      number: 7,
      englishName: "Chapter 7",
      hebrewName: "פרק ז",
      startFolio: 47,
      startSide: "a",
      endFolio: 57,
      endSide: "a",
    },
    {
      number: 8,
      englishName: "Chapter 8",
      hebrewName: "פרק ח",
      startFolio: 57,
      startSide: "a",
      endFolio: 61,
      endSide: "a",
    },
    {
      number: 9,
      englishName: "Chapter 9",
      hebrewName: "פרק ט",
      startFolio: 61,
      startSide: "a",
      endFolio: 66,
      endSide: "b",
    },
  ],
  nedarim: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 13,
      endSide: "b",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 13,
      startSide: "b",
      endFolio: 20,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 20,
      startSide: "b",
      endFolio: 32,
      endSide: "b",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 32,
      startSide: "b",
      endFolio: 45,
      endSide: "a",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 45,
      startSide: "b",
      endFolio: 48,
      endSide: "b",
    },
    {
      number: 6,
      englishName: "Chapter 6",
      hebrewName: "פרק ו",
      startFolio: 49,
      startSide: "a",
      endFolio: 53,
      endSide: "b",
    },
    {
      number: 7,
      englishName: "Chapter 7",
      hebrewName: "פרק ז",
      startFolio: 54,
      startSide: "a",
      endFolio: 60,
      endSide: "a",
    },
    {
      number: 8,
      englishName: "Chapter 8",
      hebrewName: "פרק ח",
      startFolio: 60,
      startSide: "a",
      endFolio: 63,
      endSide: "b",
    },
    {
      number: 9,
      englishName: "Chapter 9",
      hebrewName: "פרק ט",
      startFolio: 64,
      startSide: "a",
      endFolio: 66,
      endSide: "b",
    },
    {
      number: 10,
      englishName: "Chapter 10",
      hebrewName: "פרק י",
      startFolio: 66,
      startSide: "b",
      endFolio: 79,
      endSide: "a",
    },
    {
      number: 11,
      englishName: "Chapter 11",
      hebrewName: "פרק יא",
      startFolio: 79,
      startSide: "a",
      endFolio: 91,
      endSide: "b",
    },
  ],
  niddah: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 12,
      endSide: "b",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 13,
      startSide: "a",
      endFolio: 21,
      endSide: "a",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 21,
      startSide: "a",
      endFolio: 31,
      endSide: "b",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 31,
      startSide: "b",
      endFolio: 39,
      endSide: "b",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 40,
      startSide: "a",
      endFolio: 48,
      endSide: "a",
    },
    {
      number: 6,
      englishName: "Chapter 6",
      hebrewName: "פרק ו",
      startFolio: 48,
      startSide: "a",
      endFolio: 54,
      endSide: "b",
    },
    {
      number: 7,
      englishName: "Chapter 7",
      hebrewName: "פרק ז",
      startFolio: 54,
      startSide: "b",
      endFolio: 57,
      endSide: "a",
    },
    {
      number: 8,
      englishName: "Chapter 8",
      hebrewName: "פרק ח",
      startFolio: 57,
      startSide: "b",
      endFolio: 59,
      endSide: "a",
    },
    {
      number: 9,
      englishName: "Chapter 9",
      hebrewName: "פרק ט",
      startFolio: 59,
      startSide: "b",
      endFolio: 64,
      endSide: "b",
    },
    {
      number: 10,
      englishName: "Chapter 10",
      hebrewName: "פרק י",
      startFolio: 64,
      startSide: "b",
      endFolio: 73,
      endSide: "a",
    },
  ],
  pesachim: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 21,
      endSide: "a",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 21,
      startSide: "a",
      endFolio: 42,
      endSide: "a",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 42,
      startSide: "a",
      endFolio: 50,
      endSide: "a",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 50,
      startSide: "a",
      endFolio: 57,
      endSide: "b",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 58,
      startSide: "a",
      endFolio: 65,
      endSide: "b",
    },
    {
      number: 6,
      englishName: "Chapter 6",
      hebrewName: "פרק ו",
      startFolio: 65,
      startSide: "b",
      endFolio: 73,
      endSide: "b",
    },
    {
      number: 7,
      englishName: "Chapter 7",
      hebrewName: "פרק ז",
      startFolio: 74,
      startSide: "a",
      endFolio: 86,
      endSide: "b",
    },
    {
      number: 8,
      englishName: "Chapter 8",
      hebrewName: "פרק ח",
      startFolio: 87,
      startSide: "a",
      endFolio: 92,
      endSide: "b",
    },
    {
      number: 9,
      englishName: "Chapter 9",
      hebrewName: "פרק ט",
      startFolio: 92,
      startSide: "b",
      endFolio: 99,
      endSide: "a",
    },
    {
      number: 10,
      englishName: "Chapter 10",
      hebrewName: "פרק י",
      startFolio: 99,
      startSide: "b",
      endFolio: 121,
      endSide: "b",
    },
  ],
  "rosh hashanah": [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 22,
      endSide: "a",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 22,
      startSide: "a",
      endFolio: 25,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 25,
      startSide: "b",
      endFolio: 29,
      endSide: "b",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 29,
      startSide: "b",
      endFolio: 35,
      endSide: "a",
    },
  ],
  sanhedrin: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 18,
      endSide: "a",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 18,
      startSide: "a",
      endFolio: 22,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 23,
      startSide: "a",
      endFolio: 31,
      endSide: "b",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 32,
      startSide: "a",
      endFolio: 39,
      endSide: "b",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 40,
      startSide: "a",
      endFolio: 42,
      endSide: "a",
    },
    {
      number: 6,
      englishName: "Chapter 6",
      hebrewName: "פרק ו",
      startFolio: 42,
      startSide: "b",
      endFolio: 49,
      endSide: "a",
    },
    {
      number: 7,
      englishName: "Chapter 7",
      hebrewName: "פרק ז",
      startFolio: 49,
      startSide: "b",
      endFolio: 68,
      endSide: "a",
    },
    {
      number: 8,
      englishName: "Chapter 8",
      hebrewName: "פרק ח",
      startFolio: 68,
      startSide: "b",
      endFolio: 75,
      endSide: "a",
    },
    {
      number: 9,
      englishName: "Chapter 9",
      hebrewName: "פרק ט",
      startFolio: 75,
      startSide: "a",
      endFolio: 84,
      endSide: "a",
    },
    {
      number: 10,
      englishName: "Chapter 10",
      hebrewName: "פרק י",
      startFolio: 84,
      startSide: "b",
      endFolio: 90,
      endSide: "a",
    },
    {
      number: 11,
      englishName: "Chapter 11",
      hebrewName: "פרק יא",
      startFolio: 90,
      startSide: "a",
      endFolio: 113,
      endSide: "b",
    },
  ],
  shabbat: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 20,
      endSide: "b",
    },
    {
      number: 2,
      englishName: "BaMeh Madlikin",
      hebrewName: "פרק ב",
      startFolio: 20,
      startSide: "b",
      endFolio: 36,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Kirah",
      hebrewName: "פרק ג",
      startFolio: 36,
      startSide: "b",
      endFolio: 47,
      endSide: "b",
    },
    {
      number: 4,
      englishName: "BaMeh Tomnin",
      hebrewName: "פרק ד",
      startFolio: 47,
      startSide: "b",
      endFolio: 51,
      endSide: "b",
    },
    {
      number: 5,
      englishName: "BaMeh Beheimah",
      hebrewName: "פרק ה",
      startFolio: 51,
      startSide: "b",
      endFolio: 56,
      endSide: "b",
    },
    {
      number: 6,
      englishName: "BaMeh Ishah",
      hebrewName: "פרק ו",
      startFolio: 57,
      startSide: "a",
      endFolio: 67,
      endSide: "b",
    },
    {
      number: 7,
      englishName: "Kelal Gadol",
      hebrewName: "פרק ז",
      startFolio: 67,
      startSide: "b",
      endFolio: 76,
      endSide: "b",
    },
    {
      number: 8,
      englishName: "HaMotzi Yayin",
      hebrewName: "פרק ח",
      startFolio: 76,
      startSide: "b",
      endFolio: 82,
      endSide: "a",
    },
    {
      number: 9,
      englishName: "Amar Rabbi Akiva",
      hebrewName: "פרק ט",
      startFolio: 82,
      startSide: "a",
      endFolio: 90,
      endSide: "b",
    },
    {
      number: 10,
      englishName: "Chapter 10",
      hebrewName: "פרק י",
      startFolio: 90,
      startSide: "b",
      endFolio: 96,
      endSide: "a",
    },
    {
      number: 11,
      englishName: "Chapter 11",
      hebrewName: "פרק יא",
      startFolio: 96,
      startSide: "a",
      endFolio: 102,
      endSide: "a",
    },
    {
      number: 12,
      englishName: "Chapter 12",
      hebrewName: "פרק יב",
      startFolio: 102,
      startSide: "b",
      endFolio: 105,
      endSide: "a",
    },
    {
      number: 13,
      englishName: "Chapter 13",
      hebrewName: "פרק יג",
      startFolio: 105,
      startSide: "a",
      endFolio: 107,
      endSide: "a",
    },
    {
      number: 14,
      englishName: "Chapter 14",
      hebrewName: "פרק יד",
      startFolio: 107,
      startSide: "a",
      endFolio: 111,
      endSide: "b",
    },
    {
      number: 15,
      englishName: "Chapter 15",
      hebrewName: "פרק טו",
      startFolio: 111,
      startSide: "b",
      endFolio: 115,
      endSide: "a",
    },
    {
      number: 16,
      englishName: "Chapter 16",
      hebrewName: "פרק טז",
      startFolio: 115,
      startSide: "a",
      endFolio: 122,
      endSide: "b",
    },
    {
      number: 17,
      englishName: "Chapter 17",
      hebrewName: "פרק יז",
      startFolio: 122,
      startSide: "b",
      endFolio: 126,
      endSide: "b",
    },
    {
      number: 18,
      englishName: "Chapter 18",
      hebrewName: "פרק יח",
      startFolio: 126,
      startSide: "b",
      endFolio: 129,
      endSide: "b",
    },
    {
      number: 19,
      englishName: "Chapter 19",
      hebrewName: "פרק יט",
      startFolio: 130,
      startSide: "a",
      endFolio: 137,
      endSide: "b",
    },
    {
      number: 20,
      englishName: "Chapter 20",
      hebrewName: "פרק כ",
      startFolio: 137,
      startSide: "b",
      endFolio: 141,
      endSide: "b",
    },
    {
      number: 21,
      englishName: "Chapter 21",
      hebrewName: "פרק כא",
      startFolio: 141,
      startSide: "b",
      endFolio: 143,
      endSide: "a",
    },
    {
      number: 22,
      englishName: "Chapter 22",
      hebrewName: "פרק כב",
      startFolio: 143,
      startSide: "b",
      endFolio: 148,
      endSide: "a",
    },
    {
      number: 23,
      englishName: "Chapter 23",
      hebrewName: "פרק כג",
      startFolio: 148,
      startSide: "a",
      endFolio: 153,
      endSide: "a",
    },
    {
      number: 24,
      englishName: "Chapter 24",
      hebrewName: "פרק כד",
      startFolio: 153,
      startSide: "a",
      endFolio: 157,
      endSide: "b",
    },
  ],
  shevuot: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 14,
      endSide: "a",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 14,
      startSide: "a",
      endFolio: 19,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 19,
      startSide: "b",
      endFolio: 29,
      endSide: "b",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 30,
      startSide: "a",
      endFolio: 36,
      endSide: "b",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 36,
      startSide: "b",
      endFolio: 38,
      endSide: "b",
    },
    {
      number: 6,
      englishName: "Chapter 6",
      hebrewName: "פרק ו",
      startFolio: 38,
      startSide: "b",
      endFolio: 44,
      endSide: "b",
    },
    {
      number: 7,
      englishName: "Chapter 7",
      hebrewName: "פרק ז",
      startFolio: 44,
      startSide: "b",
      endFolio: 49,
      endSide: "a",
    },
    {
      number: 8,
      englishName: "Chapter 8",
      hebrewName: "פרק ח",
      startFolio: 49,
      startSide: "a",
      endFolio: 49,
      endSide: "b",
    },
  ],
  sotah: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 14,
      endSide: "a",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 14,
      startSide: "a",
      endFolio: 19,
      endSide: "a",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 19,
      startSide: "a",
      endFolio: 23,
      endSide: "b",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 23,
      startSide: "b",
      endFolio: 27,
      endSide: "b",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 27,
      startSide: "b",
      endFolio: 31,
      endSide: "a",
    },
    {
      number: 6,
      englishName: "Chapter 6",
      hebrewName: "פרק ו",
      startFolio: 31,
      startSide: "a",
      endFolio: 32,
      endSide: "a",
    },
    {
      number: 7,
      englishName: "Chapter 7",
      hebrewName: "פרק ז",
      startFolio: 32,
      startSide: "a",
      endFolio: 42,
      endSide: "a",
    },
    {
      number: 8,
      englishName: "Chapter 8",
      hebrewName: "פרק ח",
      startFolio: 42,
      startSide: "a",
      endFolio: 44,
      endSide: "b",
    },
    {
      number: 9,
      englishName: "Chapter 9",
      hebrewName: "פרק ט",
      startFolio: 44,
      startSide: "b",
      endFolio: 49,
      endSide: "b",
    },
  ],
  sukkah: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 20,
      endSide: "b",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 20,
      startSide: "b",
      endFolio: 29,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 29,
      startSide: "b",
      endFolio: 42,
      endSide: "b",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 42,
      startSide: "b",
      endFolio: 50,
      endSide: "a",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 50,
      startSide: "a",
      endFolio: 56,
      endSide: "b",
    },
  ],
  taanit: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 15,
      endSide: "a",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 15,
      startSide: "a",
      endFolio: 18,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 18,
      startSide: "b",
      endFolio: 26,
      endSide: "a",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 26,
      startSide: "a",
      endFolio: 31,
      endSide: "b",
    },
  ],
  tamid: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 25,
      startSide: "b",
      endFolio: 28,
      endSide: "b",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 28,
      startSide: "b",
      endFolio: 30,
      endSide: "a",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 30,
      startSide: "a",
      endFolio: 30,
      endSide: "b",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 30,
      startSide: "b",
      endFolio: 32,
      endSide: "b",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 32,
      startSide: "b",
      endFolio: 33,
      endSide: "a",
    },
    {
      number: 6,
      englishName: "Chapter 6",
      hebrewName: "פרק ו",
      startFolio: 33,
      startSide: "a",
      endFolio: 33,
      endSide: "a",
    },
    {
      number: 7,
      englishName: "Chapter 7",
      hebrewName: "פרק ז",
      startFolio: 33,
      startSide: "b",
      endFolio: 33,
      endSide: "b",
    },
  ],
  temurah: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 13,
      endSide: "b",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 14,
      startSide: "a",
      endFolio: 17,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 17,
      startSide: "b",
      endFolio: 21,
      endSide: "b",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 21,
      startSide: "b",
      endFolio: 24,
      endSide: "a",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 24,
      startSide: "b",
      endFolio: 27,
      endSide: "b",
    },
    {
      number: 6,
      englishName: "Chapter 6",
      hebrewName: "פרק ו",
      startFolio: 28,
      startSide: "a",
      endFolio: 31,
      endSide: "a",
    },
    {
      number: 7,
      englishName: "Chapter 7",
      hebrewName: "פרק ז",
      startFolio: 31,
      startSide: "a",
      endFolio: 34,
      endSide: "a",
    },
  ],
  yevamot: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 17,
      endSide: "a",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 17,
      startSide: "a",
      endFolio: 26,
      endSide: "a",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 26,
      startSide: "a",
      endFolio: 35,
      endSide: "a",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 35,
      startSide: "b",
      endFolio: 50,
      endSide: "a",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 50,
      startSide: "a",
      endFolio: 53,
      endSide: "b",
    },
    {
      number: 6,
      englishName: "Chapter 6",
      hebrewName: "פרק ו",
      startFolio: 53,
      startSide: "b",
      endFolio: 66,
      endSide: "a",
    },
    {
      number: 7,
      englishName: "Chapter 7",
      hebrewName: "פרק ז",
      startFolio: 66,
      startSide: "a",
      endFolio: 70,
      endSide: "a",
    },
    {
      number: 8,
      englishName: "Chapter 8",
      hebrewName: "פרק ח",
      startFolio: 70,
      startSide: "a",
      endFolio: 84,
      endSide: "a",
    },
    {
      number: 9,
      englishName: "Chapter 9",
      hebrewName: "פרק ט",
      startFolio: 84,
      startSide: "a",
      endFolio: 87,
      endSide: "b",
    },
    {
      number: 10,
      englishName: "Chapter 10",
      hebrewName: "פרק י",
      startFolio: 87,
      startSide: "b",
      endFolio: 97,
      endSide: "a",
    },
    {
      number: 11,
      englishName: "Chapter 11",
      hebrewName: "פרק יא",
      startFolio: 97,
      startSide: "a",
      endFolio: 101,
      endSide: "a",
    },
    {
      number: 12,
      englishName: "Chapter 12",
      hebrewName: "פרק יב",
      startFolio: 101,
      startSide: "a",
      endFolio: 106,
      endSide: "b",
    },
    {
      number: 13,
      englishName: "Chapter 13",
      hebrewName: "פרק יג",
      startFolio: 107,
      startSide: "a",
      endFolio: 112,
      endSide: "b",
    },
    {
      number: 14,
      englishName: "Chapter 14",
      hebrewName: "פרק יד",
      startFolio: 112,
      startSide: "b",
      endFolio: 114,
      endSide: "b",
    },
    {
      number: 15,
      englishName: "Chapter 15",
      hebrewName: "פרק טו",
      startFolio: 114,
      startSide: "b",
      endFolio: 118,
      endSide: "b",
    },
    {
      number: 16,
      englishName: "Chapter 16",
      hebrewName: "פרק טז",
      startFolio: 119,
      startSide: "a",
      endFolio: 122,
      endSide: "b",
    },
  ],
  yoma: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 21,
      endSide: "b",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 22,
      startSide: "a",
      endFolio: 28,
      endSide: "a",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 28,
      startSide: "a",
      endFolio: 39,
      endSide: "a",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 39,
      startSide: "a",
      endFolio: 46,
      endSide: "b",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 47,
      startSide: "a",
      endFolio: 62,
      endSide: "a",
    },
    {
      number: 6,
      englishName: "Chapter 6",
      hebrewName: "פרק ו",
      startFolio: 62,
      startSide: "a",
      endFolio: 68,
      endSide: "b",
    },
    {
      number: 7,
      englishName: "Chapter 7",
      hebrewName: "פרק ז",
      startFolio: 68,
      startSide: "b",
      endFolio: 73,
      endSide: "b",
    },
    {
      number: 8,
      englishName: "Chapter 8",
      hebrewName: "פרק ח",
      startFolio: 73,
      startSide: "b",
      endFolio: 88,
      endSide: "a",
    },
  ],
  zevachim: [
    {
      number: 1,
      englishName: "Chapter 1",
      hebrewName: "פרק א",
      startFolio: 2,
      startSide: "a",
      endFolio: 15,
      endSide: "b",
    },
    {
      number: 2,
      englishName: "Chapter 2",
      hebrewName: "פרק ב",
      startFolio: 15,
      startSide: "b",
      endFolio: 31,
      endSide: "b",
    },
    {
      number: 3,
      englishName: "Chapter 3",
      hebrewName: "פרק ג",
      startFolio: 31,
      startSide: "b",
      endFolio: 36,
      endSide: "b",
    },
    {
      number: 4,
      englishName: "Chapter 4",
      hebrewName: "פרק ד",
      startFolio: 36,
      startSide: "b",
      endFolio: 47,
      endSide: "a",
    },
    {
      number: 5,
      englishName: "Chapter 5",
      hebrewName: "פרק ה",
      startFolio: 47,
      startSide: "a",
      endFolio: 57,
      endSide: "b",
    },
    {
      number: 6,
      englishName: "Chapter 6",
      hebrewName: "פרק ו",
      startFolio: 58,
      startSide: "a",
      endFolio: 66,
      endSide: "a",
    },
    {
      number: 7,
      englishName: "Chapter 7",
      hebrewName: "פרק ז",
      startFolio: 66,
      startSide: "a",
      endFolio: 70,
      endSide: "b",
    },
    {
      number: 8,
      englishName: "Chapter 8",
      hebrewName: "פרק ח",
      startFolio: 70,
      startSide: "b",
      endFolio: 83,
      endSide: "a",
    },
    {
      number: 9,
      englishName: "Chapter 9",
      hebrewName: "פרק ט",
      startFolio: 83,
      startSide: "a",
      endFolio: 88,
      endSide: "b",
    },
    {
      number: 10,
      englishName: "Chapter 10",
      hebrewName: "פרק י",
      startFolio: 89,
      startSide: "a",
      endFolio: 92,
      endSide: "a",
    },
    {
      number: 11,
      englishName: "Chapter 11",
      hebrewName: "פרק יא",
      startFolio: 92,
      startSide: "a",
      endFolio: 98,
      endSide: "b",
    },
    {
      number: 12,
      englishName: "Chapter 12",
      hebrewName: "פרק יב",
      startFolio: 98,
      startSide: "b",
      endFolio: 106,
      endSide: "a",
    },
    {
      number: 13,
      englishName: "Chapter 13",
      hebrewName: "פרק יג",
      startFolio: 106,
      startSide: "a",
      endFolio: 112,
      endSide: "a",
    },
    {
      number: 14,
      englishName: "Chapter 14",
      hebrewName: "פרק יד",
      startFolio: 112,
      startSide: "a",
      endFolio: 120,
      endSide: "b",
    },
  ],
};
