// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/chavrutai-redesign/Homepage.tsx": () => import("../components/mockups/chavrutai-redesign/Homepage.tsx"),
  "./components/mockups/chavrutai-redesign/ReadingPage.tsx": () => import("../components/mockups/chavrutai-redesign/ReadingPage.tsx")
};
