/**
 * Mishnah-Talmud Mapping Data
 * Generated from Sefaria's Mishnah Map CSV
 * Source: https://github.com/Sefaria/Sefaria-Project/blob/master/data/Mishnah%20Map.csv
 */

export interface MishnahMapping {
  book: string;
  tractate: string;
  mishnahChapter: number;
  startMishnah: number;
  endMishnah: number;
  startDaf: string;
  startLine: number;
  endDaf: string;
  endLine: number;
}

export const MISHNAH_MAP_DATA: MishnahMapping[] = [
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 1,
    "startMishnah": 1,
    "endMishnah": 2,
    "startDaf": "2a",
    "startLine": 1,
    "endDaf": "2a",
    "endLine": 5
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 1,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "11b",
    "startLine": 16,
    "endDaf": "11b",
    "endLine": 17
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 1,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "13a",
    "startLine": 5,
    "endDaf": "13a",
    "endLine": 9
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 2,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "15b",
    "startLine": 9,
    "endDaf": "15b",
    "endLine": 10
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 2,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "25a",
    "startLine": 5,
    "endDaf": "25a",
    "endLine": 5
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 2,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "26a",
    "startLine": 22,
    "endDaf": "26a",
    "endLine": 22
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 2,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "27b",
    "startLine": 14,
    "endDaf": "27b",
    "endLine": 15
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 2,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "29b",
    "startLine": 10,
    "endDaf": "29b",
    "endLine": 10
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 2,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "29b",
    "startLine": 11,
    "endDaf": "29b",
    "endLine": 13
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 2,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "29b",
    "startLine": 14,
    "endDaf": "29b",
    "endLine": 15
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 3,
    "startMishnah": 1,
    "endMishnah": 2,
    "startDaf": "31b",
    "startLine": 14,
    "endDaf": "32a",
    "endLine": 3
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 3,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "35a",
    "startLine": 11,
    "endDaf": "35a",
    "endLine": 12
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 3,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "35a",
    "startLine": 13,
    "endDaf": "35a",
    "endLine": 13
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 3,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "35a",
    "startLine": 14,
    "endDaf": "35a",
    "endLine": 15
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 3,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "35b",
    "startLine": 21,
    "endDaf": "36a",
    "endLine": 2
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 4,
    "startMishnah": 1,
    "endMishnah": 2,
    "startDaf": "36b",
    "startLine": 16,
    "endDaf": "36b",
    "endLine": 19
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 4,
    "startMishnah": 3,
    "endMishnah": 4,
    "startDaf": "42b",
    "startLine": 12,
    "endDaf": "43a",
    "endLine": 4
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 4,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "45a",
    "startLine": 2,
    "endDaf": "45a",
    "endLine": 2
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 4,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "45b",
    "startLine": 6,
    "endDaf": "45b",
    "endLine": 6
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 4,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "46b",
    "startLine": 10,
    "endDaf": "46b",
    "endLine": 11
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 5,
    "startMishnah": 1,
    "endMishnah": 2,
    "startDaf": "47a",
    "startLine": 12,
    "endDaf": "47b",
    "endLine": 1
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 5,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "52b",
    "startLine": 18,
    "endDaf": "53a",
    "endLine": 1
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 5,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "53b",
    "startLine": 2,
    "endDaf": "53b",
    "endLine": 2
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 5,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "54b",
    "startLine": 10,
    "endDaf": "54b",
    "endLine": 11
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 5,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "55a",
    "startLine": 9,
    "endDaf": "55a",
    "endLine": 9
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 5,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "55a",
    "startLine": 17,
    "endDaf": "55a",
    "endLine": 17
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 5,
    "startMishnah": 8,
    "endMishnah": 8,
    "startDaf": "56b",
    "startLine": 10,
    "endDaf": "56b",
    "endLine": 11
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 6,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "58a",
    "startLine": 1,
    "endDaf": "58a",
    "endLine": 1
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 6,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "63a",
    "startLine": 2,
    "endDaf": "63a",
    "endLine": 2
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 6,
    "startMishnah": 2,
    "endMishnah": 3,
    "startDaf": "63a",
    "startLine": 18,
    "endDaf": "63b",
    "endLine": 1
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 6,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "64b",
    "startLine": 5,
    "endDaf": "64b",
    "endLine": 5
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 6,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "64b",
    "startLine": 13,
    "endDaf": "64b",
    "endLine": 14
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 6,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "64b",
    "startLine": 15,
    "endDaf": "64b",
    "endLine": 15
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 6,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "64b",
    "startLine": 16,
    "endDaf": "65a",
    "endLine": 4
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 7,
    "startMishnah": 1,
    "endMishnah": 2,
    "startDaf": "66a",
    "startLine": 7,
    "endDaf": "66a",
    "endLine": 10
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 7,
    "startMishnah": 3,
    "endMishnah": 4,
    "startDaf": "66b",
    "startLine": 13,
    "endDaf": "67a",
    "endLine": 2
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 7,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "68a",
    "startLine": 7,
    "endDaf": "68b",
    "endLine": 2
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 7,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "69a",
    "startLine": 23,
    "endDaf": "69b",
    "endLine": 4
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 8,
    "startMishnah": 1,
    "endMishnah": 2,
    "startDaf": "70b",
    "startLine": 15,
    "endDaf": "71b",
    "endLine": 6
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 8,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "75b",
    "startLine": 13,
    "endDaf": "75b",
    "endLine": 15
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 8,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "77a",
    "startLine": 7,
    "endDaf": "77a",
    "endLine": 7
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 8,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "77b",
    "startLine": 7,
    "endDaf": "77b",
    "endLine": 7
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 8,
    "startMishnah": 6,
    "endMishnah": 7,
    "startDaf": "77b",
    "startLine": 10,
    "endDaf": "78a",
    "endLine": 2
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 8,
    "startMishnah": 8,
    "endMishnah": 8,
    "startDaf": "79b",
    "startLine": 11,
    "endDaf": "79b",
    "endLine": 11
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 8,
    "startMishnah": 9,
    "endMishnah": 9,
    "startDaf": "79b",
    "startLine": 12,
    "endDaf": "79b",
    "endLine": 12
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 8,
    "startMishnah": 10,
    "endMishnah": 10,
    "startDaf": "80a",
    "startLine": 1,
    "endDaf": "80a",
    "endLine": 4
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 8,
    "startMishnah": 11,
    "endMishnah": 11,
    "startDaf": "81b",
    "startLine": 14,
    "endDaf": "81b",
    "endLine": 15
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 8,
    "startMishnah": 12,
    "endMishnah": 12,
    "startDaf": "82a",
    "startLine": 13,
    "endDaf": "82a",
    "endLine": 16
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 9,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "83a",
    "startLine": 15,
    "endDaf": "83a",
    "endLine": 19
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 9,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "84a",
    "startLine": 6,
    "endDaf": "84a",
    "endLine": 7
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 9,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "84a",
    "startLine": 8,
    "endDaf": "84a",
    "endLine": 8
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 9,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "84a",
    "startLine": 9,
    "endDaf": "84a",
    "endLine": 9
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 9,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "85b",
    "startLine": 15,
    "endDaf": "85b",
    "endLine": 16
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 9,
    "startMishnah": 6,
    "endMishnah": 7,
    "startDaf": "86a",
    "startLine": 13,
    "endDaf": "86a",
    "endLine": 14
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 9,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "88a",
    "startLine": 5,
    "endDaf": "88a",
    "endLine": 5
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 10,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "89a",
    "startLine": 1,
    "endDaf": "89a",
    "endLine": 1
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 10,
    "startMishnah": 2,
    "endMishnah": 4,
    "startDaf": "89a",
    "startLine": 8,
    "endDaf": "89a",
    "endLine": 11
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 10,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "90b",
    "startLine": 10,
    "endDaf": "90b",
    "endLine": 11
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 10,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "90b",
    "startLine": 12,
    "endDaf": "90b",
    "endLine": 12
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 10,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "90b",
    "startLine": 13,
    "endDaf": "90b",
    "endLine": 13
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 10,
    "startMishnah": 8,
    "endMishnah": 8,
    "startDaf": "91a",
    "startLine": 20,
    "endDaf": "91a",
    "endLine": 21
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 11,
    "startMishnah": 1,
    "endMishnah": 2,
    "startDaf": "92a",
    "startLine": 6,
    "endDaf": "92a",
    "endLine": 7
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 11,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "93a",
    "startLine": 15,
    "endDaf": "93a",
    "endLine": 15
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 11,
    "startMishnah": 3,
    "endMishnah": 4,
    "startDaf": "93b",
    "startLine": 15,
    "endDaf": "93b",
    "endLine": 17
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 11,
    "startMishnah": 5,
    "endMishnah": 6,
    "startDaf": "94b",
    "startLine": 13,
    "endDaf": "94b",
    "endLine": 14
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 11,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "95b",
    "startLine": 3,
    "endDaf": "95b",
    "endLine": 3
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 11,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "96b",
    "startLine": 18,
    "endDaf": "97a",
    "endLine": 1
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 11,
    "startMishnah": 8,
    "endMishnah": 8,
    "startDaf": "97a",
    "startLine": 12,
    "endDaf": "97a",
    "endLine": 13
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 12,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "98b",
    "startLine": 6,
    "endDaf": "98b",
    "endLine": 10
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 12,
    "startMishnah": 2,
    "endMishnah": 3,
    "startDaf": "103a",
    "startLine": 1,
    "endDaf": "103a",
    "endLine": 3
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 12,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "103b",
    "startLine": 13,
    "endDaf": "103b",
    "endLine": 14
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 12,
    "startMishnah": 5,
    "endMishnah": 6,
    "startDaf": "104a",
    "startLine": 20,
    "endDaf": "104b",
    "endLine": 1
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 13,
    "startMishnah": 1,
    "endMishnah": 2,
    "startDaf": "106a",
    "startLine": 9,
    "endDaf": "106a",
    "endLine": 12
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 13,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "108a",
    "startLine": 17,
    "endDaf": "108a",
    "endLine": 20
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 13,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "109a",
    "startLine": 1,
    "endDaf": "109a",
    "endLine": 2
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 13,
    "startMishnah": 4,
    "endMishnah": 5,
    "startDaf": "109b",
    "startLine": 4,
    "endDaf": "109b",
    "endLine": 6
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 13,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "110a",
    "startLine": 17,
    "endDaf": "110a",
    "endLine": 17
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 13,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "110a",
    "startLine": 20,
    "endDaf": "110a",
    "endLine": 21
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 13,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "110a",
    "startLine": 28,
    "endDaf": "110b",
    "endLine": 1
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 13,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "111a",
    "startLine": 18,
    "endDaf": "111b",
    "endLine": 3
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 13,
    "startMishnah": 8,
    "endMishnah": 8,
    "startDaf": "111b",
    "startLine": 15,
    "endDaf": "111b",
    "endLine": 18
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 14,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "112a",
    "startLine": 11,
    "endDaf": "112a",
    "endLine": 12
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 14,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "112a",
    "startLine": 13,
    "endDaf": "112b",
    "endLine": 3
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 14,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "112b",
    "startLine": 4,
    "endDaf": "112b",
    "endLine": 8
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 14,
    "startMishnah": 4,
    "endMishnah": 5,
    "startDaf": "112b",
    "startLine": 9,
    "endDaf": "112b",
    "endLine": 9
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 14,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "112b",
    "startLine": 10,
    "endDaf": "112b",
    "endLine": 10
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 14,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "112b",
    "startLine": 11,
    "endDaf": "112b",
    "endLine": 11
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 14,
    "startMishnah": 8,
    "endMishnah": 8,
    "startDaf": "112b",
    "startLine": 12,
    "endDaf": "112b",
    "endLine": 12
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 14,
    "startMishnah": 9,
    "endMishnah": 9,
    "startDaf": "112b",
    "startLine": 13,
    "endDaf": "112b",
    "endLine": 14
  },
  {
    "book": "Mishnah Zevachim",
    "tractate": "Zevachim",
    "mishnahChapter": 14,
    "startMishnah": 10,
    "endMishnah": 10,
    "startDaf": "112b",
    "startLine": 15,
    "endDaf": "113a",
    "endLine": 2
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 1,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "2a",
    "startLine": 1,
    "endDaf": "2a",
    "endLine": 3
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 1,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "6a",
    "startLine": 19,
    "endDaf": "6a",
    "endLine": 21
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 1,
    "startMishnah": 2,
    "endMishnah": 3,
    "startDaf": "11a",
    "startLine": 18,
    "endDaf": "11a",
    "endLine": 18
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 1,
    "startMishnah": 3,
    "endMishnah": 4,
    "startDaf": "11b",
    "startLine": 13,
    "endDaf": "12a",
    "endLine": 7
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 1,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "12b",
    "startLine": 12,
    "endDaf": "12b",
    "endLine": 12
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 2,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "13a",
    "startLine": 7,
    "endDaf": "13a",
    "endLine": 8
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 2,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "13b",
    "startLine": 15,
    "endDaf": "13b",
    "endLine": 15
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 2,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "14b",
    "startLine": 20,
    "endDaf": "14b",
    "endLine": 20
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 2,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "15a",
    "startLine": 7,
    "endDaf": "15a",
    "endLine": 8
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 2,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "15b",
    "startLine": 11,
    "endDaf": "15b",
    "endLine": 11
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 2,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "16a",
    "startLine": 1,
    "endDaf": "16a",
    "endLine": 4
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 3,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "17a",
    "startLine": 16,
    "endDaf": "17a",
    "endLine": 17
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 3,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "18a",
    "startLine": 11,
    "endDaf": "18a",
    "endLine": 11
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 3,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "22a",
    "startLine": 6,
    "endDaf": "22a",
    "endLine": 7
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 3,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "23a",
    "startLine": 12,
    "endDaf": "23a",
    "endLine": 14
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 3,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "25a",
    "startLine": 1,
    "endDaf": "25a",
    "endLine": 1
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 3,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "26a",
    "startLine": 2,
    "endDaf": "26a",
    "endLine": 2
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 3,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "26a",
    "startLine": 13,
    "endDaf": "26a",
    "endLine": 13
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 3,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "27a",
    "startLine": 3,
    "endDaf": "27a",
    "endLine": 4
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 3,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "27a",
    "startLine": 11,
    "endDaf": "27a",
    "endLine": 14
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 3,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "28a",
    "startLine": 6,
    "endDaf": "28a",
    "endLine": 7
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 4,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "38a",
    "startLine": 4,
    "endDaf": "38a",
    "endLine": 4
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 4,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "44b",
    "startLine": 2,
    "endDaf": "44b",
    "endLine": 2
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 4,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "44b",
    "startLine": 12,
    "endDaf": "44b",
    "endLine": 12
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 4,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "45b",
    "startLine": 2,
    "endDaf": "45b",
    "endLine": 7
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 4,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "49a",
    "startLine": 16,
    "endDaf": "49a",
    "endLine": 19
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 4,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "50b",
    "startLine": 4,
    "endDaf": "50b",
    "endLine": 5
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 4,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "51b",
    "startLine": 2,
    "endDaf": "51b",
    "endLine": 2
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 5,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "52b",
    "startLine": 12,
    "endDaf": "52b",
    "endLine": 14
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 5,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "55a",
    "startLine": 10,
    "endDaf": "55a",
    "endLine": 10
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 5,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "59a",
    "startLine": 1,
    "endDaf": "59a",
    "endLine": 5
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 5,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "59b",
    "startLine": 5,
    "endDaf": "59b",
    "endLine": 6
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 5,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "60a",
    "startLine": 6,
    "endDaf": "60a",
    "endLine": 8
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 5,
    "startMishnah": 6,
    "endMishnah": 7,
    "startDaf": "61a",
    "startLine": 5,
    "endDaf": "61a",
    "endLine": 10
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 5,
    "startMishnah": 8,
    "endMishnah": 8,
    "startDaf": "63a",
    "startLine": 1,
    "endDaf": "63a",
    "endLine": 1
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 5,
    "startMishnah": 9,
    "endMishnah": 9,
    "startDaf": "63a",
    "startLine": 9,
    "endDaf": "63a",
    "endLine": 10
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 6,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "72b",
    "startLine": 19,
    "endDaf": "72b",
    "endLine": 20
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 6,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "74b",
    "startLine": 3,
    "endDaf": "74b",
    "endLine": 3
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 6,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "74b",
    "startLine": 10,
    "endDaf": "74b",
    "endLine": 11
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 6,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "75a",
    "startLine": 14,
    "endDaf": "75a",
    "endLine": 14
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 6,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "75b",
    "startLine": 2,
    "endDaf": "75b",
    "endLine": 2
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 6,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "76a",
    "startLine": 1,
    "endDaf": "76a",
    "endLine": 1
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 6,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "76b",
    "startLine": 4,
    "endDaf": "76b",
    "endLine": 4
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 6,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "76b",
    "startLine": 9,
    "endDaf": "76b",
    "endLine": 9
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 7,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "76b",
    "startLine": 15,
    "endDaf": "77a",
    "endLine": 2
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 7,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "77b",
    "startLine": 1,
    "endDaf": "77b",
    "endLine": 1
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 7,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "78a",
    "startLine": 5,
    "endDaf": "78a",
    "endLine": 6
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 7,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "78b",
    "startLine": 1,
    "endDaf": "78b",
    "endLine": 1
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 7,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "78b",
    "startLine": 20,
    "endDaf": "78b",
    "endLine": 22
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 7,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "79a",
    "startLine": 15,
    "endDaf": "79a",
    "endLine": 15
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 7,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "79b",
    "startLine": 12,
    "endDaf": "79b",
    "endLine": 12
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 7,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "81a",
    "startLine": 12,
    "endDaf": "81b",
    "endLine": 1
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 7,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "82a",
    "startLine": 10,
    "endDaf": "82a",
    "endLine": 11
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 8,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "83b",
    "startLine": 10,
    "endDaf": "83b",
    "endLine": 12
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 8,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "85a",
    "startLine": 4,
    "endDaf": "85a",
    "endLine": 7
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 8,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "85b",
    "startLine": 11,
    "endDaf": "85b",
    "endLine": 12
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 8,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "86a",
    "startLine": 7,
    "endDaf": "86a",
    "endLine": 19
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 8,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "86a",
    "startLine": 28,
    "endDaf": "86a",
    "endLine": 29
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 8,
    "startMishnah": 6,
    "endMishnah": 7,
    "startDaf": "86b",
    "startLine": 11,
    "endDaf": "87a",
    "endLine": 3
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 9,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "87a",
    "startLine": 21,
    "endDaf": "87a",
    "endLine": 23
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 9,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "87b",
    "startLine": 19,
    "endDaf": "87b",
    "endLine": 22
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 9,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "88a",
    "startLine": 15,
    "endDaf": "88a",
    "endLine": 20
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 9,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "89a",
    "startLine": 20,
    "endDaf": "89b",
    "endLine": 3
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 9,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "90a",
    "startLine": 3,
    "endDaf": "90a",
    "endLine": 5
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 9,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "90b",
    "startLine": 5,
    "endDaf": "90b",
    "endLine": 5
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 9,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "92a",
    "startLine": 2,
    "endDaf": "92a",
    "endLine": 4
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 9,
    "startMishnah": 8,
    "endMishnah": 8,
    "startDaf": "93a",
    "startLine": 11,
    "endDaf": "93a",
    "endLine": 13
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 9,
    "startMishnah": 9,
    "endMishnah": 9,
    "startDaf": "93b",
    "startLine": 20,
    "endDaf": "94a",
    "endLine": 1
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 10,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "63b",
    "startLine": 9,
    "endDaf": "63b",
    "endLine": 10
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 10,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "64b",
    "startLine": 2,
    "endDaf": "64b",
    "endLine": 2
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 10,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "65a",
    "startLine": 4,
    "endDaf": "65a",
    "endLine": 7
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 10,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "66a",
    "startLine": 17,
    "endDaf": "66a",
    "endLine": 18
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 10,
    "startMishnah": 4,
    "endMishnah": 5,
    "startDaf": "67b",
    "startLine": 4,
    "endDaf": "67b",
    "endLine": 5
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 10,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "68a",
    "startLine": 11,
    "endDaf": "68a",
    "endLine": 12
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 10,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "68b",
    "startLine": 11,
    "endDaf": "68b",
    "endLine": 11
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 10,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "70a",
    "startLine": 16,
    "endDaf": "70a",
    "endLine": 16
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 10,
    "startMishnah": 8,
    "endMishnah": 9,
    "startDaf": "71a",
    "startLine": 7,
    "endDaf": "71a",
    "endLine": 9
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 11,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "94a",
    "startLine": 11,
    "endDaf": "94a",
    "endLine": 11
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 11,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "95b",
    "startLine": 3,
    "endDaf": "95b",
    "endLine": 3
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 11,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "96a",
    "startLine": 3,
    "endDaf": "96a",
    "endLine": 3
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 11,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "96a",
    "startLine": 4,
    "endDaf": "96a",
    "endLine": 6
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 11,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "96a",
    "startLine": 7,
    "endDaf": "96a",
    "endLine": 11
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 11,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "96a",
    "startLine": 12,
    "endDaf": "96a",
    "endLine": 14
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 11,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "99b",
    "startLine": 8,
    "endDaf": "99b",
    "endLine": 14
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 11,
    "startMishnah": 8,
    "endMishnah": 8,
    "startDaf": "100a",
    "startLine": 5,
    "endDaf": "100a",
    "endLine": 7
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 11,
    "startMishnah": 9,
    "endMishnah": 9,
    "startDaf": "100b",
    "startLine": 3,
    "endDaf": "100b",
    "endLine": 5
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 12,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "100b",
    "startLine": 9,
    "endDaf": "100b",
    "endLine": 10
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 12,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "102b",
    "startLine": 10,
    "endDaf": "102b",
    "endLine": 15
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 12,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "103a",
    "startLine": 4,
    "endDaf": "103a",
    "endLine": 5
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 12,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "103b",
    "startLine": 8,
    "endDaf": "103b",
    "endLine": 11
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 12,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "104a",
    "startLine": 4,
    "endDaf": "104a",
    "endLine": 4
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 12,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "104b",
    "startLine": 2,
    "endDaf": "104b",
    "endLine": 4
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 13,
    "startMishnah": 1,
    "endMishnah": 2,
    "startDaf": "104b",
    "startLine": 13,
    "endDaf": "104b",
    "endLine": 16
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 13,
    "startMishnah": 3,
    "endMishnah": 4,
    "startDaf": "106b",
    "startLine": 14,
    "endDaf": "106b",
    "endLine": 16
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 13,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "107a",
    "startLine": 9,
    "endDaf": "107a",
    "endLine": 10
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 13,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "107a",
    "startLine": 20,
    "endDaf": "107b",
    "endLine": 1
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 13,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "107b",
    "startLine": 2,
    "endDaf": "107b",
    "endLine": 2
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 13,
    "startMishnah": 8,
    "endMishnah": 8,
    "startDaf": "107b",
    "startLine": 3,
    "endDaf": "107b",
    "endLine": 6
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 13,
    "startMishnah": 9,
    "endMishnah": 9,
    "startDaf": "108a",
    "startLine": 21,
    "endDaf": "108a",
    "endLine": 22
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 13,
    "startMishnah": 9,
    "endMishnah": 9,
    "startDaf": "108b",
    "startLine": 19,
    "endDaf": "108b",
    "endLine": 19
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 13,
    "startMishnah": 10,
    "endMishnah": 10,
    "startDaf": "109a",
    "startLine": 4,
    "endDaf": "109a",
    "endLine": 5
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 13,
    "startMishnah": 10,
    "endMishnah": 10,
    "startDaf": "109a",
    "startLine": 14,
    "endDaf": "109a",
    "endLine": 14
  },
  {
    "book": "Mishnah Menachot",
    "tractate": "Menachot",
    "mishnahChapter": 13,
    "startMishnah": 11,
    "endMishnah": 11,
    "startDaf": "110a",
    "startLine": 14,
    "endDaf": "110a",
    "endLine": 14
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 1,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "2a",
    "startLine": 1,
    "endDaf": "2a",
    "endLine": 1
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 1,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "13a",
    "startLine": 12,
    "endDaf": "13a",
    "endLine": 12
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 1,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "13b",
    "startLine": 11,
    "endDaf": "13b",
    "endLine": 11
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 1,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "14a",
    "startLine": 1,
    "endDaf": "14a",
    "endLine": 1
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 1,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "15b",
    "startLine": 7,
    "endDaf": "15b",
    "endLine": 8
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 1,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "18a",
    "startLine": 9,
    "endDaf": "18a",
    "endLine": 9
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 1,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "18a",
    "startLine": 11,
    "endDaf": "18a",
    "endLine": 11
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 1,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "19b",
    "startLine": 12,
    "endDaf": "19b",
    "endLine": 12
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 1,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "22a",
    "startLine": 13,
    "endDaf": "22a",
    "endLine": 13
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 1,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "23b",
    "startLine": 11,
    "endDaf": "23b",
    "endLine": 11
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 1,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "24a",
    "startLine": 7,
    "endDaf": "24a",
    "endLine": 7
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 1,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "24b",
    "startLine": 10,
    "endDaf": "24b",
    "endLine": 10
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 1,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "25a",
    "startLine": 11,
    "endDaf": "25a",
    "endLine": 11
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 1,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "25b",
    "startLine": 5,
    "endDaf": "25b",
    "endLine": 5
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 1,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "25b",
    "startLine": 9,
    "endDaf": "25b",
    "endLine": 10
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 1,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "26b",
    "startLine": 4,
    "endDaf": "26b",
    "endLine": 4
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 1,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "26b",
    "startLine": 8,
    "endDaf": "26b",
    "endLine": 8
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 1,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "26b",
    "startLine": 10,
    "endDaf": "26b",
    "endLine": 12
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 2,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "27a",
    "startLine": 1,
    "endDaf": "27a",
    "endLine": 1
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 2,
    "startMishnah": 2,
    "endMishnah": 3,
    "startDaf": "30b",
    "startLine": 11,
    "endDaf": "30b",
    "endLine": 12
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 2,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "31a",
    "startLine": 12,
    "endDaf": "31a",
    "endLine": 12
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 2,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "32a",
    "startLine": 4,
    "endDaf": "32a",
    "endLine": 4
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 2,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "32a",
    "startLine": 17,
    "endDaf": "32a",
    "endLine": 18
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 2,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "33a",
    "startLine": 9,
    "endDaf": "33a",
    "endLine": 9
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 2,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "37a",
    "startLine": 2,
    "endDaf": "37a",
    "endLine": 3
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 2,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "38b",
    "startLine": 7,
    "endDaf": "38b",
    "endLine": 8
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 2,
    "startMishnah": 8,
    "endMishnah": 8,
    "startDaf": "39b",
    "startLine": 20,
    "endDaf": "40a",
    "endLine": 1
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 2,
    "startMishnah": 9,
    "endMishnah": 9,
    "startDaf": "41a",
    "startLine": 9,
    "endDaf": "41b",
    "endLine": 1
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 2,
    "startMishnah": 10,
    "endMishnah": 10,
    "startDaf": "41b",
    "startLine": 8,
    "endDaf": "41b",
    "endLine": 10
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 3,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "42a",
    "startLine": 3,
    "endDaf": "42a",
    "endLine": 5
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 3,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "54a",
    "startLine": 13,
    "endDaf": "54a",
    "endLine": 14
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 3,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "56a",
    "startLine": 2,
    "endDaf": "56a",
    "endLine": 2
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 3,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "56b",
    "startLine": 9,
    "endDaf": "56b",
    "endLine": 9
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 3,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "58b",
    "startLine": 13,
    "endDaf": "58b",
    "endLine": 13
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 3,
    "startMishnah": 6,
    "endMishnah": 7,
    "startDaf": "59a",
    "startLine": 6,
    "endDaf": "59a",
    "endLine": 7
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 4,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "68a",
    "startLine": 1,
    "endDaf": "68a",
    "endLine": 2
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 4,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "69b",
    "startLine": 10,
    "endDaf": "69b",
    "endLine": 10
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 4,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "70b",
    "startLine": 1,
    "endDaf": "70b",
    "endLine": 1
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 4,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "71a",
    "startLine": 16,
    "endDaf": "71a",
    "endLine": 16
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 4,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "72a",
    "startLine": 11,
    "endDaf": "72b",
    "endLine": 7
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 4,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "74a",
    "startLine": 16,
    "endDaf": "74b",
    "endLine": 1
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 4,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "76a",
    "startLine": 1,
    "endDaf": "76a",
    "endLine": 2
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 4,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "77a",
    "startLine": 11,
    "endDaf": "77a",
    "endLine": 13
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 5,
    "startMishnah": 1,
    "endMishnah": 2,
    "startDaf": "78a",
    "startLine": 5,
    "endDaf": "78a",
    "endLine": 14
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 5,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "81b",
    "startLine": 4,
    "endDaf": "81b",
    "endLine": 5
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 5,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "82a",
    "startLine": 9,
    "endDaf": "82a",
    "endLine": 9
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 5,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "82a",
    "startLine": 11,
    "endDaf": "82a",
    "endLine": 12
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 5,
    "startMishnah": 3,
    "endMishnah": 4,
    "startDaf": "83a",
    "startLine": 6,
    "endDaf": "83a",
    "endLine": 8
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 5,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "83a",
    "startLine": 15,
    "endDaf": "83a",
    "endLine": 15
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 6,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "83b",
    "startLine": 3,
    "endDaf": "83b",
    "endLine": 4
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 6,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "85a",
    "startLine": 7,
    "endDaf": "85a",
    "endLine": 8
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 6,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "86a",
    "startLine": 6,
    "endDaf": "86a",
    "endLine": 7
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 6,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "86b",
    "startLine": 7,
    "endDaf": "86b",
    "endLine": 7
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 6,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "87a",
    "startLine": 2,
    "endDaf": "87a",
    "endLine": 2
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 6,
    "startMishnah": 5,
    "endMishnah": 6,
    "startDaf": "87a",
    "startLine": 14,
    "endDaf": "87b",
    "endLine": 2
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 6,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "88a",
    "startLine": 7,
    "endDaf": "88a",
    "endLine": 7
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 7,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "89b",
    "startLine": 3,
    "endDaf": "89b",
    "endLine": 5
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 7,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "93b",
    "startLine": 21,
    "endDaf": "93b",
    "endLine": 21
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 7,
    "startMishnah": 2,
    "endMishnah": 3,
    "startDaf": "96a",
    "startLine": 5,
    "endDaf": "96a",
    "endLine": 6
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 7,
    "startMishnah": 4,
    "endMishnah": 5,
    "startDaf": "96b",
    "startLine": 6,
    "endDaf": "96b",
    "endLine": 8
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 7,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "100b",
    "startLine": 3,
    "endDaf": "100b",
    "endLine": 3
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 8,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "104b",
    "startLine": 6,
    "endDaf": "104b",
    "endLine": 7
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 8,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "103b",
    "startLine": 16,
    "endDaf": "104a",
    "endLine": 1
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 8,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "107b",
    "startLine": 15,
    "endDaf": "107b",
    "endLine": 15
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 8,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "108a",
    "startLine": 2,
    "endDaf": "108a",
    "endLine": 2
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 8,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "109a",
    "startLine": 9,
    "endDaf": "109a",
    "endLine": 9
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 8,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "113a",
    "startLine": 16,
    "endDaf": "113a",
    "endLine": 16
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 8,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "113a",
    "startLine": 18,
    "endDaf": "113a",
    "endLine": 19
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 8,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "116a",
    "startLine": 17,
    "endDaf": "116b",
    "endLine": 1
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 8,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "116b",
    "startLine": 17,
    "endDaf": "117a",
    "endLine": 2
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 9,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "117b",
    "startLine": 6,
    "endDaf": "117b",
    "endLine": 9
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 9,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "122a",
    "startLine": 10,
    "endDaf": "122a",
    "endLine": 12
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 9,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "123a",
    "startLine": 4,
    "endDaf": "123a",
    "endLine": 7
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 9,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "124a",
    "startLine": 18,
    "endDaf": "124a",
    "endLine": 19
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 9,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "124b",
    "startLine": 25,
    "endDaf": "125a",
    "endLine": 2
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 9,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "126b",
    "startLine": 11,
    "endDaf": "126b",
    "endLine": 11
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 9,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "127a",
    "startLine": 20,
    "endDaf": "127b",
    "endLine": 2
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 9,
    "startMishnah": 8,
    "endMishnah": 8,
    "startDaf": "129b",
    "startLine": 10,
    "endDaf": "129b",
    "endLine": 10
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 10,
    "startMishnah": 1,
    "endMishnah": 2,
    "startDaf": "130a",
    "startLine": 1,
    "endDaf": "130a",
    "endLine": 7
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 10,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "132a",
    "startLine": 17,
    "endDaf": "132a",
    "endLine": 19
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 10,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "134a",
    "startLine": 8,
    "endDaf": "134a",
    "endLine": 8
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 10,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "134b",
    "startLine": 14,
    "endDaf": "134b",
    "endLine": 14
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 11,
    "startMishnah": 1,
    "endMishnah": 2,
    "startDaf": "135a",
    "startLine": 1,
    "endDaf": "135a",
    "endLine": 7
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 12,
    "startMishnah": 1,
    "endMishnah": 2,
    "startDaf": "138b",
    "startLine": 3,
    "endDaf": "138b",
    "endLine": 4
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 12,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "140b",
    "startLine": 13,
    "endDaf": "140b",
    "endLine": 14
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 12,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "141a",
    "startLine": 5,
    "endDaf": "141a",
    "endLine": 5
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 12,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "141a",
    "startLine": 16,
    "endDaf": "141a",
    "endLine": 16
  },
  {
    "book": "Mishnah Chullin",
    "tractate": "Chullin",
    "mishnahChapter": 12,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "142a",
    "startLine": 2,
    "endDaf": "142a",
    "endLine": 2
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 1,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "2a",
    "startLine": 1,
    "endDaf": "2a",
    "endLine": 1
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 1,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "3b",
    "startLine": 15,
    "endDaf": "3b",
    "endLine": 15
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 1,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "5b",
    "startLine": 7,
    "endDaf": "5b",
    "endLine": 8
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 1,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "7b",
    "startLine": 15,
    "endDaf": "7b",
    "endLine": 15
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 1,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "9a",
    "startLine": 3,
    "endDaf": "9a",
    "endLine": 4
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 1,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "9a",
    "startLine": 5,
    "endDaf": "9a",
    "endLine": 6
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 1,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "12a",
    "startLine": 1,
    "endDaf": "12a",
    "endLine": 1
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 1,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "12b",
    "startLine": 16,
    "endDaf": "12b",
    "endLine": 17
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 1,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "13a",
    "startLine": 4,
    "endDaf": "13a",
    "endLine": 7
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 2,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "13a",
    "startLine": 9,
    "endDaf": "13a",
    "endLine": 10
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 2,
    "startMishnah": 2,
    "endMishnah": 3,
    "startDaf": "14a",
    "startLine": 1,
    "endDaf": "14a",
    "endLine": 4
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 2,
    "startMishnah": 4,
    "endMishnah": 5,
    "startDaf": "16a",
    "startLine": 15,
    "endDaf": "16b",
    "endLine": 2
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 2,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "17a",
    "startLine": 21,
    "endDaf": "17b",
    "endLine": 1
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 2,
    "startMishnah": 7,
    "endMishnah": 8,
    "startDaf": "18b",
    "startLine": 13,
    "endDaf": "18b",
    "endLine": 16
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 2,
    "startMishnah": 9,
    "endMishnah": 9,
    "startDaf": "19a",
    "startLine": 2,
    "endDaf": "19a",
    "endLine": 2
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 3,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "19b",
    "startLine": 5,
    "endDaf": "19b",
    "endLine": 7
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 3,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "21b",
    "startLine": 9,
    "endDaf": "21b",
    "endLine": 9
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 3,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "23b",
    "startLine": 8,
    "endDaf": "23b",
    "endLine": 8
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 3,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "24b",
    "startLine": 5,
    "endDaf": "24b",
    "endLine": 5
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 3,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "25a",
    "startLine": 17,
    "endDaf": "25b",
    "endLine": 2
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 4,
    "startMishnah": 1,
    "endMishnah": 2,
    "startDaf": "26b",
    "startLine": 8,
    "endDaf": "26b",
    "endLine": 9
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 4,
    "startMishnah": 3,
    "endMishnah": 4,
    "startDaf": "28a",
    "startLine": 12,
    "endDaf": "28a",
    "endLine": 12
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 4,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "28b",
    "startLine": 8,
    "endDaf": "28b",
    "endLine": 8
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 4,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "28b",
    "startLine": 12,
    "endDaf": "28b",
    "endLine": 14
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 4,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "28b",
    "startLine": 17,
    "endDaf": "29a",
    "endLine": 1
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 4,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "29a",
    "startLine": 5,
    "endDaf": "29a",
    "endLine": 6
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 4,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "29b",
    "startLine": 4,
    "endDaf": "29b",
    "endLine": 4
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 4,
    "startMishnah": 8,
    "endMishnah": 8,
    "startDaf": "29b",
    "startLine": 11,
    "endDaf": "29b",
    "endLine": 11
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 4,
    "startMishnah": 9,
    "endMishnah": 9,
    "startDaf": "29b",
    "startLine": 13,
    "endDaf": "29b",
    "endLine": 13
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 4,
    "startMishnah": 10,
    "endMishnah": 10,
    "startDaf": "30a",
    "startLine": 3,
    "endDaf": "30a",
    "endLine": 3
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 5,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "31a",
    "startLine": 14,
    "endDaf": "31a",
    "endLine": 16
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 5,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "32b",
    "startLine": 9,
    "endDaf": "32b",
    "endLine": 9
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 5,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "33b",
    "startLine": 5,
    "endDaf": "33b",
    "endLine": 5
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 5,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "34a",
    "startLine": 10,
    "endDaf": "34a",
    "endLine": 10
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 5,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "35a",
    "startLine": 2,
    "endDaf": "35a",
    "endLine": 3
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 5,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "35a",
    "startLine": 10,
    "endDaf": "35a",
    "endLine": 10
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 5,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "35a",
    "startLine": 17,
    "endDaf": "35a",
    "endLine": 17
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 5,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "36a",
    "startLine": 17,
    "endDaf": "36a",
    "endLine": 17
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 5,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "36b",
    "startLine": 13,
    "endDaf": "36b",
    "endLine": 13
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 5,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "36b",
    "startLine": 16,
    "endDaf": "36b",
    "endLine": 16
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 5,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "37a",
    "startLine": 6,
    "endDaf": "37a",
    "endLine": 7
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 6,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "37a",
    "startLine": 15,
    "endDaf": "37a",
    "endLine": 15
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 6,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "38a",
    "startLine": 21,
    "endDaf": "38a",
    "endLine": 21
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 6,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "38b",
    "startLine": 10,
    "endDaf": "38b",
    "endLine": 11
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 6,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "39a",
    "startLine": 8,
    "endDaf": "39a",
    "endLine": 8
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 6,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "39a",
    "startLine": 10,
    "endDaf": "39a",
    "endLine": 10
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 6,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "39b",
    "startLine": 12,
    "endDaf": "39b",
    "endLine": 12
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 6,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "40a",
    "startLine": 5,
    "endDaf": "40a",
    "endLine": 5
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 6,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "40a",
    "startLine": 11,
    "endDaf": "40a",
    "endLine": 11
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 6,
    "startMishnah": 8,
    "endMishnah": 8,
    "startDaf": "40a",
    "startLine": 15,
    "endDaf": "40a",
    "endLine": 16
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 6,
    "startMishnah": 9,
    "endMishnah": 9,
    "startDaf": "40a",
    "startLine": 23,
    "endDaf": "40a",
    "endLine": 23
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 6,
    "startMishnah": 9,
    "endMishnah": 9,
    "startDaf": "40b",
    "startLine": 4,
    "endDaf": "40b",
    "endLine": 4
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 6,
    "startMishnah": 10,
    "endMishnah": 10,
    "startDaf": "40b",
    "startLine": 9,
    "endDaf": "40b",
    "endLine": 9
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 6,
    "startMishnah": 11,
    "endMishnah": 11,
    "startDaf": "40b",
    "startLine": 18,
    "endDaf": "40b",
    "endLine": 18
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 6,
    "startMishnah": 11,
    "endMishnah": 11,
    "startDaf": "41a",
    "startLine": 2,
    "endDaf": "41a",
    "endLine": 2
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 6,
    "startMishnah": 12,
    "endMishnah": 12,
    "startDaf": "41a",
    "startLine": 5,
    "endDaf": "41a",
    "endLine": 6
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 7,
    "startMishnah": 1,
    "endMishnah": 2,
    "startDaf": "43a",
    "startLine": 4,
    "endDaf": "43a",
    "endLine": 5
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 7,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "43b",
    "startLine": 13,
    "endDaf": "43b",
    "endLine": 13
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 7,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "43b",
    "startLine": 17,
    "endDaf": "43b",
    "endLine": 17
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 7,
    "startMishnah": 4,
    "endMishnah": 5,
    "startDaf": "44a",
    "startLine": 14,
    "endDaf": "44a",
    "endLine": 14
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 7,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "44b",
    "startLine": 1,
    "endDaf": "44b",
    "endLine": 1
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 7,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "44b",
    "startLine": 14,
    "endDaf": "44b",
    "endLine": 14
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 7,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "44b",
    "startLine": 18,
    "endDaf": "45a",
    "endLine": 3
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 7,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "45b",
    "startLine": 5,
    "endDaf": "45b",
    "endLine": 5
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 7,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "45b",
    "startLine": 11,
    "endDaf": "45b",
    "endLine": 12
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 8,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "46a",
    "startLine": 5,
    "endDaf": "46a",
    "endLine": 11
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 8,
    "startMishnah": 1,
    "endMishnah": 2,
    "startDaf": "47b",
    "startLine": 11,
    "endDaf": "47b",
    "endLine": 12
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 8,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "48a",
    "startLine": 1,
    "endDaf": "48a",
    "endLine": 2
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 8,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "48b",
    "startLine": 11,
    "endDaf": "48b",
    "endLine": 17
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 8,
    "startMishnah": 5,
    "endMishnah": 6,
    "startDaf": "49a",
    "startLine": 5,
    "endDaf": "49a",
    "endLine": 5
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 8,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "49a",
    "startLine": 11,
    "endDaf": "49a",
    "endLine": 11
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 8,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "49b",
    "startLine": 10,
    "endDaf": "49b",
    "endLine": 11
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 8,
    "startMishnah": 8,
    "endMishnah": 8,
    "startDaf": "51a",
    "startLine": 7,
    "endDaf": "51a",
    "endLine": 8
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 8,
    "startMishnah": 9,
    "endMishnah": 9,
    "startDaf": "51b",
    "startLine": 12,
    "endDaf": "52a",
    "endLine": 1
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 8,
    "startMishnah": 10,
    "endMishnah": 10,
    "startDaf": "52b",
    "startLine": 3,
    "endDaf": "52b",
    "endLine": 4
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 9,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "53a",
    "startLine": 1,
    "endDaf": "53a",
    "endLine": 2
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 9,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "54b",
    "startLine": 10,
    "endDaf": "54b",
    "endLine": 10
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 9,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "55b",
    "startLine": 9,
    "endDaf": "55b",
    "endLine": 9
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 9,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "56b",
    "startLine": 7,
    "endDaf": "56b",
    "endLine": 8
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 9,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "57a",
    "startLine": 6,
    "endDaf": "57a",
    "endLine": 6
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 9,
    "startMishnah": 5,
    "endMishnah": 6,
    "startDaf": "57b",
    "startLine": 6,
    "endDaf": "57b",
    "endLine": 9
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 9,
    "startMishnah": 7,
    "endMishnah": 7,
    "startDaf": "58b",
    "startLine": 4,
    "endDaf": "58b",
    "endLine": 5
  },
  {
    "book": "Mishnah Bekhorot",
    "tractate": "Bekhorot",
    "mishnahChapter": 9,
    "startMishnah": 8,
    "endMishnah": 8,
    "startDaf": "60a",
    "startLine": 7,
    "endDaf": "60a",
    "endLine": 9
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 1,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "2a",
    "startLine": 1,
    "endDaf": "2a",
    "endLine": 3
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 1,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "5a",
    "startLine": 16,
    "endDaf": "5a",
    "endLine": 16
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 1,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "5b",
    "startLine": 7,
    "endDaf": "5b",
    "endLine": 7
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 1,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "6b",
    "startLine": 8,
    "endDaf": "6b",
    "endLine": 8
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 1,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "7a",
    "startLine": 11,
    "endDaf": "7a",
    "endLine": 11
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 2,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "7b",
    "startLine": 15,
    "endDaf": "7b",
    "endLine": 16
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 2,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "8a",
    "startLine": 5,
    "endDaf": "8a",
    "endLine": 5
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 2,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "8b",
    "startLine": 9,
    "endDaf": "8b",
    "endLine": 9
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 2,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "8b",
    "startLine": 15,
    "endDaf": "8b",
    "endLine": 16
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 2,
    "startMishnah": 3,
    "endMishnah": 4,
    "startDaf": "10a",
    "startLine": 2,
    "endDaf": "10a",
    "endLine": 4
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 2,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "13a",
    "startLine": 9,
    "endDaf": "13a",
    "endLine": 9
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 2,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "13b",
    "startLine": 6,
    "endDaf": "13b",
    "endLine": 7
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 3,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "13b",
    "startLine": 17,
    "endDaf": "13b",
    "endLine": 18
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 3,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "14a",
    "startLine": 5,
    "endDaf": "14a",
    "endLine": 6
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 3,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "14b",
    "startLine": 19,
    "endDaf": "14b",
    "endLine": 19
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 3,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "14b",
    "startLine": 22,
    "endDaf": "14b",
    "endLine": 22
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 3,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "15a",
    "startLine": 5,
    "endDaf": "15a",
    "endLine": 6
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 4,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "17a",
    "startLine": 9,
    "endDaf": "17a",
    "endLine": 12
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 4,
    "startMishnah": 2,
    "endMishnah": 3,
    "startDaf": "17b",
    "startLine": 6,
    "endDaf": "17b",
    "endLine": 7
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 4,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "18a",
    "startLine": 9,
    "endDaf": "18a",
    "endLine": 10
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 4,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "18a",
    "startLine": 13,
    "endDaf": "18a",
    "endLine": 15
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 5,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "19a",
    "startLine": 4,
    "endDaf": "19a",
    "endLine": 5
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 5,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "19b",
    "startLine": 13,
    "endDaf": "19b",
    "endLine": 13
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 5,
    "startMishnah": 2,
    "endMishnah": 2,
    "startDaf": "20a",
    "startLine": 7,
    "endDaf": "20a",
    "endLine": 8
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 5,
    "startMishnah": 3,
    "endMishnah": 3,
    "startDaf": "20a",
    "startLine": 9,
    "endDaf": "20a",
    "endLine": 9
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 5,
    "startMishnah": 4,
    "endMishnah": 4,
    "startDaf": "20a",
    "startLine": 10,
    "endDaf": "20a",
    "endLine": 10
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 5,
    "startMishnah": 5,
    "endMishnah": 5,
    "startDaf": "20b",
    "startLine": 2,
    "endDaf": "20b",
    "endLine": 2
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 5,
    "startMishnah": 6,
    "endMishnah": 6,
    "startDaf": "21a",
    "startLine": 5,
    "endDaf": "21a",
    "endLine": 6
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 6,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "21b",
    "startLine": 13,
    "endDaf": "21b",
    "endLine": 13
  },
  {
    "book": "Mishnah Arakhin",
    "tractate": "Arakhin",
    "mishnahChapter": 6,
    "startMishnah": 1,
    "endMishnah": 1,
    "startDaf": "22a",
    "startLine": 14,
    "endDaf": "22a",
    "endLine": 15
  }
];

/**
 * Get the section number for the first Mishnah of a given chapter
 * @param tractate - Tractate name (case-insensitive)
 * @param chapter - Chapter number
 * @param page - Talmud page (e.g., "90a", "2b")
 * @returns Section number or null if not found
 */
export function getMishnahSection(tractate: string, chapter: number, page: string): number | null {
  const normalizedTractate = tractate.toLowerCase();
  const normalizedPage = page.toLowerCase();

  // Find the first mishnah of the given chapter that starts on the given page
  const mapping = MISHNAH_MAP_DATA.find(
    m => 
      m.tractate.toLowerCase() === normalizedTractate &&
      m.mishnahChapter === chapter &&
      m.startMishnah === 1 &&
      m.startDaf.toLowerCase() === normalizedPage
  );

  return mapping ? mapping.startLine : null;
}

/**
 * Get the chapter number for a given page
 * @param tractate - Tractate name (case-insensitive)
 * @param page - Talmud page (e.g., "90a", "2b")
 * @returns Chapter number or null if not found
 */
export function getChapterForPage(tractate: string, page: string): number | null {
  const normalizedTractate = tractate.toLowerCase();
  const normalizedPage = page.toLowerCase();

  const mapping = MISHNAH_MAP_DATA.find(
    m => 
      m.tractate.toLowerCase() === normalizedTractate &&
      m.startDaf.toLowerCase() === normalizedPage &&
      m.startMishnah === 1
  );

  return mapping ? mapping.mishnahChapter : null;
}

/**
 * Get all mappings for a specific tractate
 * @param tractate - Tractate name (case-insensitive)
 * @returns Array of all Mishnah mappings for the tractate
 */
export function getTractateMap(tractate: string): MishnahMapping[] {
  const normalizedTractate = tractate.toLowerCase();
  return MISHNAH_MAP_DATA.filter(
    m => m.tractate.toLowerCase() === normalizedTractate
  );
}

/**
 * Get all unique tractates in the mapping
 * @returns Array of unique tractate names
 */
export function getAllTractates(): string[] {
  const tractates = new Set(MISHNAH_MAP_DATA.map(m => m.tractate));
  return Array.from(tractates).sort();
}

